### ISSUE TITLE
ClassNotFound: GFileSystemFactoryFull (Ghidra 10.1+)

### ISSUE THREAD

**Issue by Vhati** [lab313ru/ghidra_amiga_ldr#17]
When adding the extension to Ghidra, I got an exception.

"Extension version for [...] is incompatible with Ghidra"

I edited "ghidra_amiga_ldr\extension.properties" to set "version=10.0" to "10.1.1" (Ghidra's current version) to see what would happen.
.
.
After installing the extension, restarting Ghidra, and attempting to import an Amiga executable, I get a different exception.

"ClassNotFoundException: ghidra.formats.gfilesystem.factory.GFileSystemFactoryFull"
.
.
The following discussion might help...

https://github.com/NationalSecurityAgency/ghidra/issues/3781#issuecomment-998980469
> "[...] a non-standard GFileSystem (from a custom extension or plugin) installed that is built against the previous version of Ghidra."
>
> "[...] the "GFileSystemFactoryFull" interface was deleted between 10.0 and 10.1. [...]"
>
> "[...] GFileSystemFactoryByteProvider is the newer interface. There are a few methods on the base GFileSystem interface that have changed as well, to remove File / InputStreams from method signatures and replace them with ByteProviders. [...]"

.
Sorry I can't offer a PR for what's probably a trivial revision. This is my first time trying Ghidra.

**Comment by lab313ru** [comment]
Hi,

Upgrading to the new GHIDRA version is not that simple:) I'll try to update the loader during this week.

**Comment by lab313ru** [comment]
Check it: https://github.com/lab313ru/ghidra_amiga_ldr/releases/tag/v2.1

**Comment by Vhati** [comment]
That seems to work. Thanks. 👍

I'm noobishly trying to glean the logic in a relatively simple AMOS game. The "defined strings" window shows hardcoded text, which is all consolidated in one section of the file. Ghidra's not finding the funcs that reference those strings though. No familiar landmarks in the disassembly. Maybe I should look into Amiga-based/UAE debuggers then, so I can pause and know where I'm at...

**Comment by nicodex** [comment]
It's not that unusual that only the start of the table (separated by null-chars) has a xref, and the string is 'referenced' by the index or the offset...
