### ISSUE TITLE
howto?

### ISSUE THREAD

**Issue by wothke** [lab313ru/ghidra_amiga_ldr#21]
this seems to be a useful plugin .. but it is an annoying and a unnessarry waste of time that there is no doc for howto build/install/use it. a short coverage of the below key points would fix that;

1) prerequitites: install Java (same JRE that was used to build Ghirda - ps: there should be a better error message when the build detects an "incorrect" Java version) and Gradle
2) build: using the gradle command mentioned in build.gradle. 
3) install: manually copy the build result from the "dist" folder to your %GHIDRA%/Extensions/Ghidra/ folder (it seems silly that this is not performed automatically - since that folder had already to be configured for the build command..).  activate plugin in Ghidra (see File/Install Extensions menu) and restart Ghidra
4) usage: within Ghidra there is no plugin-menu - instead the plugin automatically triggers the first time a suitable hunk-file is opened (i.e. you need to remove/re-add files that you already had in your existing project..)

**Comment by lab313ru** [comment]
First of all, you have to install the plugin. No building manually is required.
Second is just drag-n-drop your hunk file into ghidra and it will analyze everything for you. The rest must me your competence, not mine.

**Comment by wothke** [comment]
WTF are you talking about? Your repository contains no pre-built plugin so of course I have to build it manually! Second: you just confirm the UI limitation that I've mentioned: there is no UI (e.g. an added entry in the "Analysis" menu) that would allow to trigger the analysis for a file that was already *PREVIOUSLY* in a Ghidra project - it only works for files that are newly dragged into the workspace.
It is sad that you seem to think that things that may be obvious to you, will automatically be obvious to potential users of your plugin. But do what you please, you have my feedback for how you might make for a more enjoyable user experience.

**Comment by nicodex** [comment]
Please calm down. Plug-in installation is explained in the Ghidra documentation.

There is a binary release, but for an older Ghidra release. From time to time I'm building the plug-in and provide an updated release on my fork at https://github.com/nicodex/ghidra_amiga_ldr/releases/

This is a loader plug-in, so you have to import the binary with the plug-in.

**Comment by lab313ru** [comment]
> Please calm down. Plug-in installation is explained in the Ghidra documentation.
> 
> There is a binary release, but for an older Ghidra release. From time to time I'm building the plug-in and provide an updated release on my fork at https://github.com/nicodex/ghidra_amiga_ldr/releases/
> 
> This is a loader plug-in, so you have to import the binary with the plug-in.

Thanks!

**Comment by wothke** [comment]
> Please calm down. Plug-in installation is explained in the Ghidra documentation.
> 
> There is a binary release, but for an older Ghidra release. From time to time I'm building the plug-in and provide an updated release on my fork at https://github.com/nicodex/ghidra_amiga_ldr/releases/
> 
> This is a loader plug-in, so you have to import the binary with the plug-in.

As I said, it's a question of *unnecessarily* wasting your user's time: Will they be able to eventually figure that stuff out by searching around in other documentations? Sure, eventually. But adding a few simple bullet points in your now empty [README.md](https://github.com/lab313ru/ghidra_amiga_ldr/blob/master/README.md) would make things so much easier. It would be a good place for putting a link to your "releases" repository too.

**Comment by nicodex** [comment]
I'm just forking and trying to help, this upstream repo is not mine and there are still a lot of things to do/know to get around some issues...
