### ISSUE TITLE
How to replace label to jsr -offset(A6) from exec to other libraries

### ISSUE THREAD

**Issue by zakgi** [lab313ru/ghidra_amiga_ldr#22]
I'm having a bit of a hard time changing the label of A6-relative, negative offsets to other libraries than exec. I almost always end up renaming the exec aliases instead. The decompiler stills insist on using A5 as a parameter instead of choosing the right prototype for the syscall. Is there a simple way to just switch labels? If I double click on the alias I can see the operand references to all libraries I have selected, but clicking on the right name just points to the corresponding definition in the .fd file.

**Comment by lab313ru** [comment]
So, you've solved it?

**Comment by zakgi** [comment]
Hi Vladimir,

Thanks for getting back to me.
I'm still new to Ghidra so it was a beginner's mistake.
I was trying to modify the labels instead of using option R (i.e. Add/Edit
Reference). It works like a charm now.

Thank you for this nice tool - it's very useful and makes RE much easier
and a great learning experience.

I have two extra questions if you don't mind.

I noticed that the prototypes for library functions always specify the
arguments as pointers, so in order for the decompiler to work correctly I
have to change them to word/dword.
Is this intentional or just a first iteration?

Also, sometimes I would like to change the segment base addresses to follow
the same layout that exec uses when running on the emulator, but if I
change it  from Window->Memory Map-> Set Image Base the decompiled code
does not update the fixups.
Do I need to take some additional steps?

Thank you for your work and for making it public.

Best,
Giammarco

**Comment by lab313ru** [comment]
1. It's my workaround for Ghidra to deal with functions calling in Amiga's style
2. Try to perform reanalyze. But I don't sure if it help

**Comment by zakgi** [comment]
On Tue, Aug 30, 2022 at 10:35 AM Vladimir Kononovich <
***@***.***> wrote:

>
>    1. It's my workaround for Ghidra to deal with functions calling in
>    Amiga's style
>
>
Got it.

>
>    1. Try to perform reanalyze. But I don't sure if it help
>
> Unfortunately it didn't.

Thanks,
Giammarco
