### ISSUE TITLE
Update to 9.1-PUBLIC

### ISSUE THREAD

**Issue by Kneesnap** [lab313ru/ghidra_amiga_ldr#3]
Could we get a release for 9.1-PUBLIC?

Also, I'd like to talk to @lab313ru about an Amiga compression library, where would be the best place to talk?

**Comment by lab313ru** [comment]
Uploaded 9.1-PUBLIC supported release: https://github.com/lab313ru/ghidra_amiga_ldr/releases/tag/v1.5

Is that your email about PP2.0?

**Comment by Kneesnap** [comment]
Yep! That's me! I wasn't sure if you would receive the email so I figured I'd ask here too since I was already making an issue. But if you've received the email then that's all. Thanks for updating to 9.1 PUBLIC too.
