### ISSUE TITLE
How do we add this to Ghidra?

### ISSUE THREAD

**Issue by hippietrail** [lab313ru/ghidra_amiga_ldr#7]
From Ghidra's "Install Extensions" window clicking on the "+" it doesn't seem to work whether I select the Zip archive, or decompress it into a directory and try to select various levels of that directory.

If I copy the directory into the Ghidra/Extensions/ folder and then go the the "Install Extensions" window, it shows up, but in red with only "@extname@" in the "Name" field, the "Description" field does look correct, and the "Version" field is blank.

![amighidra](https://user-images.githubusercontent.com/533619/82425919-87c30e00-9aca-11ea-8c20-7799bc3d5dd8.PNG)

In this state it fails to recognize an Amiga executable that the "file" command does identify as being one. After restarting Ghidra nothing changes.

Do I have to first build it in Eclipse? If so, how?

**Comment by lab313ru** [comment]
I have to update it to the latest Ghidra version.

**Comment by lab313ru** [comment]
https://github.com/lab313ru/ghidra_amiga_ldr/releases/tag/v1.6
